### ISSUE TITLE
4 Sub-State (quarter step) encoder reading enhancement instead of the halfstep in original code

### ISSUE THREAD

**Issue by ardlc-1212** [jamon/pi-pico-pio-quadrature-encoder#7]
Hi, I made a "4 sub-state counting for each line on the encoder" update to the program using 2 state machines. Unfortunately I didnt had the hardware to test it so I am hoping someone with the right hardware can. Here is the code 😄 : 

[pi-pico-pio-quadrature-encoder-main.zip](https://github.com/jamon/pi-pico-pio-quadrature-encoder/files/12208122/pi-pico-pio-quadrature-encoder-main.zip)

I am happy to contribute to such a cool project I hope this becomes the new big feature <3.

Quick note: I don't have any idea about the licencing protocols so I just left them as is

Quick note 2: to read the value we have to read both of the sm and add them together.

Update: I used the y register to increment and kept the values consistent on each reading too.

With Love and Sleep Deprivation,
         Arda

**Comment by ardlc-1212** [comment]
Hello it's update time I just got my hands on an encoder and fixed a couple of bugs here and there this updated version seems to work flawlessly. I am excited to use these on my projects. (note that I didnt tried using it on pins other than 20 and 21 because my pcb layout wouldn't allow me to do so, but that shouldn't be a problem c-sdk should handle it easily)

[pi-pico-pio-quadrature-encoder-main.zip](https://github.com/jamon/pi-pico-pio-quadrature-encoder/files/12209877/pi-pico-pio-quadrature-encoder-main.zip)

**Comment by jamon** [comment]
@ardlc-1212 Is all the code you've modified/added your own work?  and do you agree to license it under the same license as the repository (MIT)?

as a side-note, if you're interested, I'm happy to grant you commit permissions, as well.

**Comment by ardlc-1212** [comment]
It is my own work and I agree to license it under the same MIT licence

Also I would love to get commit permissions, always happy to be a part of the community :)

**Comment by ardlc-1212** [comment]
@jamon Can you set up the readme, license files etc to include me and publish it. I would love to do it but I am kinda busy right now with an approaching exam. 

Here's my info if you can include that on the file too:

Arda Alıcı <ardayaozel@hotmail.com>

Thanks in advance,
       Arda

**Comment by jamon** [comment]
Yeah--It will take me a bit to get to it as well though, I need to get my test rig set back up :)

**Comment by ardlc-1212** [comment]
> It will take me a bit to get to it as well though

Yeah no problem if I can find any free time Ill try to do so, and thanks.
